export default {
    content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
    theme: {
        extend: {
            colors: {
                primary: "#775AFC",
                secondary: "#A44CEE",
                tertiary: "#FF847F",
                main3: "#2d6a4f",
                white1: "#ffffff",
                white2: "#DDE2FF",
                black1: "#271D3A",
                black2: "#010F1C",
                light1: "rgba(119, 90, 252, 0.1)",
                light2: "#989899",
                grey1: "#55585B",
                grey2: "#9A9B9C",
                grey3: "#F9F9F9",
                grey4: "#6F7276",
                grey5: "#F5F5F5",
                grey6: "#565764",
                grey7: "#F1F2F6",
                grey8: "#544D4F",
                blue1: "#4260FF",
                blue2: "#1A9FBD",
                blue3: "#3470E4",
                blue4: "#F2F1FD",
                primaryBtn: "#775AFC",
                darkBlue: "#1E2B8A",
                card1: "#4c49ea",
                card2: "#3ecd5e",
                card3: "#e44002",
                card4: "#952aff",
                card5: "#cd3e94",
                g1: "#0a9396",
                g2: "#94d2bd",
                g3: "#FF847F",
                course1: "#B7B8E5",
                course2: "#E5C9B7",
                course3: "#B7DEE6",
                course4: "#B7E6CF",
                course5: "#AEC6F4",
                skin1: "#CC926E",
                skin2: "#FFDB66",
                purple1: "#6E71CC",
                green1: "#6FCD9E",
                color1: "#ededed",
                color2: "#64c1cf",
                color3: "#b1c3c1",
                color4: "#bd9ac8",
                color5: "#6d87b5",
                color6: "#00acb5",
                color7: "#dbd3b1",
                color8: "#ffffff",
                color9: "#edf2f2",
                color10: "#4d5972",
                silverPlan: "",
            },
            fontFamily: {
                axiforma: "axiformaRegular",
                axiMedium: "axiformaMedium",
                axiSemiBold: "axiformaSemiBold",
                axiBold: "axiformaBold",
            },
        }
    },
    plugins: [],
};
